// AUTO-GENERATED by build.js — do not edit manually.
// Source: .env (local) or Vercel Environment Variables (production).
// Generated: 2026-04-02T12:56:27.562Z
//
// ⚠  SECURITY: Only PUBLIC variables are written here.
//    SERVER-ONLY vars (service role key, admin token, merchant secret)
//    are accessed exclusively by Vercel Serverless Functions via process.env.

export const ENV = Object.freeze({
  SUPABASE_URL:        `https://opnjdxstsgpbvtlqysma.supabase.co`,
  SUPABASE_ANON_KEY:   `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbmpkeHN0c2dwYnZ0bHF5c21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDE5NTMsImV4cCI6MjA5MDYxNzk1M30.oW2zVT5CkqIAw5WoigsN02iAwPYBlwuILd6frleLtZc`,
  DEMO_MODE:           false,
  ADMIN_EMAIL:         `admin@yourdomain.com`,
  ADMIN_PASSWORD:      `ChangeMe_Strong_Password_Here!`,
  PAYHERE_MERCHANT_ID: `YOUR_PAYHERE_MERCHANT_ID`,
  PAYHERE_SANDBOX:     false,
  WA_PHONE:            `94771234567`,
  WA_PHONE_2:          `94751234567`,
  POSTHOG_KEY:         ``,
  POSTHOG_HOST:        `https://app.posthog.com`,
  EMAILJS_PUBLIC_KEY:  `YOUR_EMAILJS_PUBLIC_KEY`,
  EMAILJS_SERVICE_ID:  `YOUR_EMAILJS_SERVICE_ID`,
  EMAILJS_TEMPLATE_ID: `YOUR_EMAILJS_TEMPLATE_ID`,
  EMAILJS_ADMIN_EMAIL: `admin@yourdomain.com`,
});
