#!/usr/bin/env node
/* ============================================================
   ZENMARKET — BUILD SCRIPT  (v29 — Full Stack)
   ============================================================
   Reads .env (local) or process.env (Vercel) and writes js/env.js.
   Only PUBLIC variables (safe for the browser) are written.
   SERVER-ONLY variables (service role key, admin token, etc.)
   are never written to js/env.js — they stay in process.env
   and are only accessed by Vercel Serverless Functions.

   LOCAL DEV (demo mode — no setup needed):
     The project ships with a working js/env.js for demo mode.
     You don't need to run this unless you want real credentials.

   LOCAL WITH REAL CREDENTIALS:
     cp .env.example .env      ← fill in your values
     node build.js             ← overwrites js/env.js

   VERCEL PRODUCTION:
     Set every variable in Project → Settings → Environment Variables.
     vercel.json buildCommand runs this automatically on deploy.
   ============================================================ */

const fs   = require('fs');
const path = require('path');

// ── 1. Load .env if present (local dev) ──────────────────────────
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) {
  fs.readFileSync(envFile, 'utf8').split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq < 0) return;
    const key = trimmed.slice(0, eq).trim();
    let val   = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    if (!(key in process.env)) process.env[key] = val;
  });
}

// ── 2. Read vars with safe demo fallbacks ─────────────────────────
function get(key, fallback = '') {
  const val = process.env[key];
  if (!val || !val.trim()) {
    return fallback;
  }
  return val.trim();
}

// ── 3. Validate production requirements ───────────────────────────
const demoMode = get('DEMO_MODE', 'true') === 'true';

if (demoMode) {
  if (!get('ADMIN_PASSWORD')) {
    console.error('[build] ERROR: DEMO_MODE=true but ADMIN_PASSWORD is not set.');
    process.exit(1);
  }
  console.log('[build] ℹ  Running in DEMO MODE — localStorage auth, no database required.');
} else {
  // Production checks
  const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
  const missing  = required.filter(k => !get(k));
  if (missing.length > 0) {
    console.error(`[build] ERROR: DEMO_MODE=false but missing: ${missing.join(', ')}`);
    process.exit(1);
  }
  // Warn about server-only vars (not written to env.js but needed by API routes)
  const serverVars = [
    'SUPABASE_SERVICE_ROLE_KEY',
    'ADMIN_API_TOKEN',
    'PAYHERE_MERCHANT_SECRET',
    'SITE_URL',
  ];
  serverVars.forEach(k => {
    if (!get(k)) console.warn(`[build] WARNING: ${k} is not set — needed by serverless functions`);
  });
}

// ── 4. PUBLIC vars only — safe to put in browser bundle ───────────
// NEVER add SUPABASE_SERVICE_ROLE_KEY, ADMIN_API_TOKEN, or
// PAYHERE_MERCHANT_SECRET here — those are server-only.
const env = {
  SUPABASE_URL:        get('SUPABASE_URL',        'https://YOUR_PROJECT.supabase.co'),
  SUPABASE_ANON_KEY:   get('SUPABASE_ANON_KEY',   ''),
  DEMO_MODE:           demoMode,
  ADMIN_EMAIL:         get('ADMIN_EMAIL',          'admin@zenmarket.lk'),
  ADMIN_PASSWORD:      get('ADMIN_PASSWORD',       ''),
  PAYHERE_MERCHANT_ID: get('PAYHERE_MERCHANT_ID',  'YOUR_MERCHANT_ID'),
  PAYHERE_SANDBOX:     get('PAYHERE_SANDBOX',      'true') !== 'false',
  WA_PHONE:            get('WA_PHONE',             '94771234567'),
  WA_PHONE_2:          get('WA_PHONE_2',           '94751234567'),
  POSTHOG_KEY:         get('POSTHOG_KEY',          ''),
  POSTHOG_HOST:        get('POSTHOG_HOST',         'https://app.posthog.com'),
  EMAILJS_PUBLIC_KEY:  get('EMAILJS_PUBLIC_KEY',   ''),
  EMAILJS_SERVICE_ID:  get('EMAILJS_SERVICE_ID',   ''),
  EMAILJS_TEMPLATE_ID: get('EMAILJS_TEMPLATE_ID',  ''),
  EMAILJS_ADMIN_EMAIL: get('EMAILJS_ADMIN_EMAIL',  'admin@zenmarket.lk'),
};

function jsStr(v) {
  return String(v)
    .replace(/\\/g, '\\\\')
    .replace(/`/g,  '\\`')
    .replace(/\$/g, '\\$');
}

const out = `// AUTO-GENERATED by build.js — do not edit manually.
// Source: .env (local) or Vercel Environment Variables (production).
// Generated: ${new Date().toISOString()}
//
// ⚠  SECURITY: Only PUBLIC variables are written here.
//    SERVER-ONLY vars (service role key, admin token, merchant secret)
//    are accessed exclusively by Vercel Serverless Functions via process.env.

export const ENV = Object.freeze({
  SUPABASE_URL:        \`${jsStr(env.SUPABASE_URL)}\`,
  SUPABASE_ANON_KEY:   \`${jsStr(env.SUPABASE_ANON_KEY)}\`,
  DEMO_MODE:           ${env.DEMO_MODE},
  ADMIN_EMAIL:         \`${jsStr(env.ADMIN_EMAIL)}\`,
  ADMIN_PASSWORD:      \`${jsStr(env.ADMIN_PASSWORD)}\`,
  PAYHERE_MERCHANT_ID: \`${jsStr(env.PAYHERE_MERCHANT_ID)}\`,
  PAYHERE_SANDBOX:     ${env.PAYHERE_SANDBOX},
  WA_PHONE:            \`${jsStr(env.WA_PHONE)}\`,
  WA_PHONE_2:          \`${jsStr(env.WA_PHONE_2)}\`,
  POSTHOG_KEY:         \`${jsStr(env.POSTHOG_KEY)}\`,
  POSTHOG_HOST:        \`${jsStr(env.POSTHOG_HOST)}\`,
  EMAILJS_PUBLIC_KEY:  \`${jsStr(env.EMAILJS_PUBLIC_KEY)}\`,
  EMAILJS_SERVICE_ID:  \`${jsStr(env.EMAILJS_SERVICE_ID)}\`,
  EMAILJS_TEMPLATE_ID: \`${jsStr(env.EMAILJS_TEMPLATE_ID)}\`,
  EMAILJS_ADMIN_EMAIL: \`${jsStr(env.EMAILJS_ADMIN_EMAIL)}\`,
});
`;

fs.writeFileSync(path.join(__dirname, 'js', 'env.js'), out, 'utf8');
console.log(`[build] ✓ js/env.js written (DEMO_MODE=${env.DEMO_MODE})`);
